---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    author: saikiran
spec:
  containers:
    - name: worker-app-pod
      image: dockersamples/examplevotingapp_worker
...